package mysql

const Name = "mysql"
const WildcardAll string = "*"
const Comma string = ", "
const Select string = "SELECT "
const Where = " WHERE "
const And = " AND "
const InnerJoin = " INNER JOIN "
const On = " ON "
const Equals = " = "
const EndQuery = ";"
const From = " FROM "
const InsertInto = "INSERT INTO "
const Values = " VALUES "
const Delete = "DELETE"
const Update = "UPDATE "
const Set = " SET "
